#!/usr/bin/env bash
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)
cd "$ROOT"
make build/READ2.COM build/VGA.COM build/CMODE.COM
bash tools/build-watcom-com.sh qa/input/tvframe.c build/TVFRAME.COM
